title: PyVStim Documentation
description: A github pages documenting all the funtions and logic behing each stimuli that Silies Lab uses in the experiments
theme: just-the-docs

url: https://pradeeptrimbake.github.io/PyVstim_docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
